version: '3.3'

services:
  core:
    build: server
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/media/
    entrypoint: ["sh", "entrypoint.sh"]
    ports:
      - "8000"
    env_file:
      - .env

  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - core


volumes:
  static_volume:
  media_volume:
